name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34
        with:
          user: rahulchaudhari7
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories
          output_action: commit
          committer_branch: main
          committer_message: "chore: update GitHub metrics [Skip GitHub Action]"
